<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="System.Numerics.Tensors" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoMemeVideo.Domain\PoMemeVideo.Domain.csproj" />
    <ProjectReference Include="..\PoMemeVideo.Shared\PoMemeVideo.Shared.csproj" />
  </ItemGroup>

</Project>